In [1]:
#This can be used as a code editor also as a terminal
a = [1,5,8,9]
a

[1, 5, 8, 9]

#Data Analysis packages -->numpy,pandas,data visualization (matplotlib,plotly)

4 Steps in Machine Learning Lifecycle:

1)Planning (Understanding the problem statement (gathering data resources)
   -->Kaggle,UCI,OpenGov datasets...
2)Data Preparation -->Data Retrieval,Data Exploration,Data Cleansing... -->EDA
3)Modelling (scikit-learn) -->Model creation,Model validation,Model Evalutation
4)Presentation of model (Deployment) -->AWS,Streamlit,Pythonanywhere.

In [4]:
#Installing Numerical Python package (numpy arrays)
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/57/09/fe9282ffb0217176b0185900945189b6beaec4f94ff46afb76bcd9b68e30/numpy-1.26.1-cp310-cp310-win_amd64.whl.metadata
  Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.1-cp310-cp310-win_amd64.whl (15.8 MB)



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
#Numpy (Numerical Python) -->Storing data in array format,Faster Processing,
#Perform Element wise operations,Statistical functions..
#Why numpy arrays are much faster than python lists?
a = [1,5,8,96,3]
#create two lists with huge elements (1 crore/10 lakhs)
L1 = list(range(0,999999))
L2 = list(range(0,999999))
#As we have two lists above create a new list by adding each element from above list
L3= []
for i in range(len(L1)):
    L3.append(L1[i]+L2[i])
#print(L3)

In [19]:
#Now to compute time taken -->time module
import time
#help(time)
L1 = list(range(0,999999))
L2 = list(range(0,999999))
L3 = []
start = time.time() #epoch time 1970 Jan1st
for i in range(len(L1)):
    L3.append(L1[i]+L2[i])
end = time.time()
#print(end-start)
print("Time taken is",(end-start)*1000,"milliseconds")

Time taken is 531.0392379760742 milliseconds


In [20]:
#Now same above process if we store in arrays using numpy
import numpy as np
#we create huge elements in numpy array
A1 = np.arange(0,999999)
A2 = np.arange(0,999999)
#add two arrays
start = time.time()
A3 = A1+A2
end = time.time()
print("Time taken is",(end-start)*1000,"milliseconds")

Time taken is 4.0073394775390625 milliseconds


In [25]:
#Creation of arrays and element wise operations
#Use tab and shift tab
a = np.array([1,5,8,9,63])
#a
print(a)
print(type(a))
print(a.ndim) #returns dimension of the array
print(a.size) #returns number of elementsin the array

[ 1  5  8  9 63]
<class 'numpy.ndarray'>
1
5


In [29]:
#2-dimension arrays
a = np.array([[1,8,9],
              [1,2,3],
             [12,-5,6]]
             )
print(a)
print(a.ndim)
#axis - 0 rows,axis-1columns
print(a.shape)

[[ 1  8  9]
 [ 1  2  3]
 [12 -5  6]]
2
(3, 3)


In [31]:
#Accessing elements in the array -->indexing,slicing
print(a[0]) #accessing row-wise 
print(a[0:2])

[1 8 9]
[[1 8 9]
 [1 2 3]]


In [37]:
print(a)
print(a[0:,0])

[[ 1  8  9]
 [ 1  2  3]
 [12 -5  6]]
[ 1  1 12]


In [39]:
#Accessing 2nd and 3rd row-wise/column-wise elements
print(a[1:,1:])

[[ 2  3]
 [-5  6]]


In [43]:
#Mathematical operations and Statistical functions over arrays
b = np.arange(0,9)
#b
#convert 1-d to 2-d
b = b.reshape(3,3)
#b
b = np.arange(0,9).reshape(3,3)
#b

In [42]:
a

array([[ 1,  8,  9],
       [ 1,  2,  3],
       [12, -5,  6]])

In [47]:
#print(a+b)
#print(np.add(a,b))
#print(np.subtract(a,b))
print(np.multiply(a,b)) #element wise multiplication

[[  0   8  18]
 [  3   8  15]
 [ 72 -35  48]]


In [48]:
#mean(),variance(),std(),min(),max(),minimum(),maximum()
a

array([[ 1,  8,  9],
       [ 1,  2,  3],
       [12, -5,  6]])

In [51]:
print(np.mean(a)) #sum of all elements / total of elements
print(np.mean(a,axis=0)) #row-wise (vertical)
print(np.mean(a,axis=1)) #column-wise (horizontal)

4.111111111111111
[4.66666667 1.66666667 6.        ]
[6.         2.         4.33333333]


In [53]:
print(np.var(a)) #how far the values are differing from mean
print(np.std(a)) #sqrt of variance

23.65432098765432
4.863570806275398


In [57]:
print(a)
print(b)
print(np.min(a))
print(np.minimum(a,b)) #compare each element from both array and return new array

[[ 1  8  9]
 [ 1  2  3]
 [12 -5  6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-5
[[ 0  1  2]
 [ 1  2  3]
 [ 6 -5  6]]


In [58]:
#Be confident on transformations,basic functions on numpy arrays
#Refer Numpy documentation -->numpy.org

In 2008, developer Wes McKinney started developing pandas when in need of high
performance, flexible tool for analysis of data.

Pandas gives Python the ability to work with spreadsheet-like data for fast data 
loading,manipulating,aligning and merging

**Series and DataFrame**

DataFrame respresents entire spreadsheet whereas Series is a single column of the dataframe

#Pandas -->Series(1 dimensional data representation) (column in a table)
#DataFrame -->2 dimensional data representation (table consisting of rows and columns)

In [59]:
#Pandas ->[Panel data (2008) Wes Mckinney]
#1-Dimensional data -->Series
#2-Dimensional data -->DataFrame
!pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/c4/3a/b84f90ba24d50cbbe79982d5298fb82f6208e2d85bed86b165192fc0f620/pandas-2.1.2-cp310-cp310-win_amd64.whl.metadata
  Using cached pandas-2.1.2-cp310-cp310-win_amd64.whl.metadata (18 kB)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Using cached pandas-2.1.2-cp310-cp310-win_amd64.whl (10.7 MB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [60]:
import pandas as pd

In [67]:
a = [1,5,8,9,63] #you can take list,1-D array,tuple,dictionary,scalar
b = pd.Series(a) 
#print(b)
#print(type(b))
#print(type(b.values))
#print(b.index)

In [69]:
data = {'name':'Codegnan','college':'nbkr'}
b = pd.Series(data) #keys will be the index
print(b)
#print(b.values)

name       Codegnan
college        nbkr
dtype: object
['Codegnan' 'nbkr']


In [70]:
#2-Dimensional tabular data -->DataFrame (read excel or cvs files -->read_csv/read_excel)
#Case Study on EDA (Exploratory Data Analysis) -->Titanic
data = pd.read_csv('titanic.csv')
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [73]:
#You need to get the complete information from the dataframe
type(data)
#data.ndim
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [74]:
#Access column wise data from above data
data.columns #returns columns within the dataframe

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [77]:
data['Survived']
#Need to get the categorical count from the column
data['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [78]:
data['Embarked'].value_counts() 

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [79]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [80]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [82]:
#data['Age'].value_counts()

In [ ]:
#To get better insights before we start Modifications on the dataframe we go
#for data visualization (matplotlib,plotly)
